# Generated by Django 4.2.13 on 2024-05-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('cnic', models.CharField(max_length=100)),
                ('disorder', models.CharField(max_length=255)),
                ('fee_paid', models.CharField(max_length=100)),
                ('attendant', models.CharField(max_length=100)),
            ],
        ),
    ]
